language: node_js
dist: bionic
node_js:
  - "12"
script:
  - node --version

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
  - nvm install 12
  - nvm use 12

install:
  - npm install
  - npm install -g yarn

script:
  - yarn build
  - mv build/index.html build/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master


  github_token: $github_token
  local_dir: build
  on:
    branch: master
