language: node_js
dist: bionic
node_js:
  - "20.11.0"

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g yarn

script:
  - node --version
  - yarn build
  - mv build/index.html build/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Ensure this is correctly set up in your Travis CI environment variables
  local_dir: build
  on:
    branch: master
