language: node_js
node_js:
  - "stable"

branches:
  only:
  - main

cache:
  directories:
  - node_modules

install:
  - npm install
  - npm install -g yarn

script:
  - npm test

deploy:
  provider: pages
  cleanup: false
  github_token: $github_token
  local_dir: build
  on:
    branch: master
