language: node_js
node_js:
  - "12" # Specifying a Node.js version known for broader compatibility

dist: bionic # Using Ubuntu Bionic, which has a more recent version of GLIBC

branches:
  only:
  - master

cache:
  directories:
  - node_modules

install:
  - npm install
  - npm install -g yarn

script:
  #- yarn lint # This line is commented out; remove the comment to enable linting
  - yarn build
  - mv build/index.html build/404.html # Ensures SPA routes properly handle 404 errors

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
