language: node_js
node_js:
  - "stable"
  
cache:
  directories:
  - node_modules

install:
  - yarn install

script:
  - yarn test

deploy:
  provider: pages
  cleanup: false
  github_token: $github_token
  local_dir: build
  on:
    branch: master
