language: node_js
dist: focal
node_js:
  - "20.11.0"
  - "stable"

before_install:
  - npm install -g npm@latest 
script:
  - echo "Testing..." && exit 0
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main

install:
  - npm install
  - npm install -g yarn
cache:
  directories:
  - node_modules
script:
  #- yarn lint
  - yarn build
  - mv build/index.html build/404.html

