language: node_js
dist: focal
node_js:
  - "20.11.0"
  before_install:
  - npm install -g npm@latest
"scripts": {
  "test": "echo \"No tests to run.\" && exit 0"
}
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main
